### ISSUE TITLE
Improve the View Post feature

### ISSUE THREAD

**Issue by xJonathanLEI** [xJonathanLEI/HKGolden#4]
Most part of the post viewing feature is completed. There are still improvements to make:
1. **API side**: There should be an option to load post content via mobile site, which saves over 60% of traffic and therefore speeds up loading. Although UserIDs of the authors are not presented in mobile pages, most users would not care.
2. **UI side**: The blockquote element is still not rendered and represented by [UNKNOWN].
3. **UI side**: Other text effects (strong etc.) are not rendered.

**Comment by 556556bt** [comment]
consider some option setting for textblock which make dark theme mode feasible

**Comment by xJonathanLEI** [comment]
Sure. But I am still working on the backend side. Why don't we use Skype to cooperate? ;)
